/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Appointment;
import Business.Business;
import Business.DB4OUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class CancelAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CancelAppointmentJPanel
     */private JPanel upc;
     private Business b;
     private DB4OUtil dbo4;
    public CancelAppointmentJPanel(JPanel upc, Business b, DB4OUtil dbo4) {
        initComponents();
        this.upc = upc;
        this.dbo4 = dbo4;
        this.b = dbo4.retrieveSystem();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idJTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cancelAptJBtn = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        idJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idJTxtFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Appointment Id");

        cancelAptJBtn.setText("Cancel Appointment");
        cancelAptJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAptJBtnActionPerformed(evt);
            }
        });

        backJBtn.setText("<<  Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cancel Appointment Window");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(idJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(backJBtn)
                        .addGap(44, 44, 44)
                        .addComponent(cancelAptJBtn)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAptJBtn)
                    .addComponent(backJBtn))
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idJTxtFieldActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void cancelAptJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAptJBtnActionPerformed
        // TODO add your handling code here:
       if(idJTxtField.getText().trim().length() == 0){
           JOptionPane.showMessageDialog(null, "Please enter a valid appointment id to cancel");
           
       } else {
           Appointment a = b.getAptHist().removeAppointmentToAppointmentDb(Integer.parseInt(idJTxtField.getText()));
           if(a != null){
           b.getAptHist().addScheduleToScheduleDb(a.getAppointmentDate());
           dbo4.storeSystem(b);
           JOptionPane.showMessageDialog(null, "Appointment Cancelled Successfully.");
           } else {
               JOptionPane.showMessageDialog(null,"Invalid Appointment Id, please enter valid Id");
           }
       }
        
    }//GEN-LAST:event_cancelAptJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton cancelAptJBtn;
    private javax.swing.JTextField idJTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
