/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.DB4OUtil;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class DoctorWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkArea
     */
    private JPanel upc;
    private Business b;
    private DB4OUtil dbo4;
    public DoctorWorkArea(JPanel upc, Business b, DB4OUtil dbo4) {
        initComponents();
        this.upc = upc;
        this.b = b;
        this.dbo4 = dbo4;
        docNmJLbl.setText("Welcome Doctor " + b.getD().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSchdJBtn = new javax.swing.JButton();
        viewUpcAptJBtn = new javax.swing.JButton();
        docNmJLbl = new javax.swing.JLabel();

        addSchdJBtn.setText("Add Schedule");
        addSchdJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSchdJBtnActionPerformed(evt);
            }
        });

        viewUpcAptJBtn.setText("View Upcoming Appointments");
        viewUpcAptJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpcAptJBtnActionPerformed(evt);
            }
        });

        docNmJLbl.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(docNmJLbl)
                    .addComponent(viewUpcAptJBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addSchdJBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(docNmJLbl)
                .addGap(47, 47, 47)
                .addComponent(addSchdJBtn)
                .addGap(46, 46, 46)
                .addComponent(viewUpcAptJBtn)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addSchdJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSchdJBtnActionPerformed
        // TODO add your handling code here:
        AddScheduleJPanel asp = new AddScheduleJPanel(upc, b, dbo4);
        upc.add("Add Schedule",asp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_addSchdJBtnActionPerformed

    private void viewUpcAptJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpcAptJBtnActionPerformed
        // TODO add your handling code here:
        ViewUpcomingAppointmentJPanel asp = new ViewUpcomingAppointmentJPanel(upc, b, dbo4);
        upc.add("Upcoming Appointments",asp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_viewUpcAptJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSchdJBtn;
    private javax.swing.JLabel docNmJLbl;
    private javax.swing.JButton viewUpcAptJBtn;
    // End of variables declaration//GEN-END:variables
}
