/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.DB4OUtil;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame1
     */
    
    private DB4OUtil db4oUtil;
    private Business business;
    public MainJFrame() {
        initComponents();
        db4oUtil = DB4OUtil.getInstance();
        business = db4oUtil.retrieveSystem();
        typJCmbBx.removeAllItems();
        typJCmbBx.addItem("Patient");
        typJCmbBx.addItem("Doctor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        usrTypJBtn = new javax.swing.JButton();
        typJCmbBx = new javax.swing.JComboBox();
        logOutJBtn = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usrTypJBtn.setText("Select Type");
        usrTypJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrTypJBtnActionPerformed(evt);
            }
        });

        typJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        logOutJBtn.setText("Log Out");
        logOutJBtn.setEnabled(false);
        logOutJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usrTypJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typJCmbBx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(logOutJBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(typJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(usrTypJBtn)
                .addGap(18, 18, 18)
                .addComponent(logOutJBtn)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void validateUserType(){
        String type = (String) typJCmbBx.getSelectedItem();
        if(type.equals("Patient")){
           logOutJBtn.setEnabled(true); 
          PatientWorkArea pwa = new PatientWorkArea(userProcessContainer, business, db4oUtil);
          userProcessContainer.add("Patient Work Area", pwa);
          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
          layout.next(userProcessContainer);
            
        } else {
          logOutJBtn.setEnabled(true);
          DoctorLoginJpanel dlp = new DoctorLoginJpanel(userProcessContainer, business, db4oUtil);
          userProcessContainer.add("Doctor Login Area",dlp);
          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
          layout.next(userProcessContainer);          
            
        }
    }
    
    private void usrTypJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrTypJBtnActionPerformed
        // TODO add your handling code here:
        validateUserType();
        usrTypJBtn.setEnabled(false);
        
    }//GEN-LAST:event_usrTypJBtnActionPerformed

    private void logOutJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        dummyJPanel djp = new dummyJPanel();
        userProcessContainer.add("DummyPanel",djp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        logOutJBtn.setEnabled(false);
        usrTypJBtn.setEnabled(true);
        
    }//GEN-LAST:event_logOutJBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logOutJBtn;
    private javax.swing.JComboBox typJCmbBx;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JButton usrTypJBtn;
    // End of variables declaration//GEN-END:variables
}
