/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Appointment;
import Business.Business;
import Business.DB4OUtil;
import Business.Patient;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AnanthaShankar
 */
public class ViewAvailableAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAvailableAppointmentJPanel
     */private JPanel upc;
       private Patient p;
       private Business b;
       private DB4OUtil dbo4;
    public ViewAvailableAppointmentJPanel(JPanel upc, Patient p, Business b, DB4OUtil dbo4) {
        initComponents();
        this.upc = upc;
        this.p = p;
        this.b=b;
        this.dbo4 = dbo4;
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) aptJTbl.getModel();
        dtm.setRowCount(0);
        String dt;
        Date date;
        SimpleDateFormat sf = new SimpleDateFormat("MM-dd-yyyy");
        date = Calendar.getInstance().getTime();
        dt = sf.format(date);
        int today_year = Integer.parseInt(dt.substring(6));
        int today_date = Integer.parseInt(dt.substring(3, 5));
        int today_month = Integer.parseInt(dt.substring(0, 2));
        b = dbo4.retrieveSystem();
        for(String s : b.getAptHist().getAvailableAppointments()){
            int entered_year = Integer.parseInt(s.substring(6,10));
            int entered_month = Integer.parseInt(s.substring(0, 2));
            int entered_date = Integer.parseInt(s.substring(3, 5));
            if(today_year == entered_year && today_month == entered_month && today_date > entered_date){
                
            } else {
            Object row[] = new Object[1];
            row[0]= s;
            dtm.addRow(row);}
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        aptJTbl = new javax.swing.JTable();
        createAptJBtn = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        patientNmJTxtField = new javax.swing.JTextField();
        rfrshJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        aptJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Available Appointments"
            }
        ));
        jScrollPane1.setViewportView(aptJTbl);

        createAptJBtn.setText("Create Appointment");
        createAptJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAptJBtnActionPerformed(evt);
            }
        });

        backJBtn.setText("<<  Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Patient Name");

        patientNmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNmJTxtFieldActionPerformed(evt);
            }
        });

        rfrshJBtn.setText("Refresh Appointments");
        rfrshJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfrshJBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Book Appointment Window");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(backJBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(patientNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rfrshJBtn)
                                .addGap(18, 18, 18)
                                .addComponent(createAptJBtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(patientNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJBtn)
                    .addComponent(rfrshJBtn)
                    .addComponent(createAptJBtn))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAptJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAptJBtnActionPerformed
        // TODO add your handling code here:
        b = dbo4.retrieveSystem();
        int selectedRow = aptJTbl.getSelectedRow();
        if(selectedRow >= 0){
          if(patientNmJTxtField.getText().trim().length() == 0){
              JOptionPane.showMessageDialog(null, "Please enter a valid name");
          }  else {
              
              p.setName(patientNmJTxtField.getText());
              String result = b.getAptHist().deleteScheduleFromScheduleDb((String)aptJTbl.getValueAt(selectedRow, 0));
              
              if(result == null){  //Concurrency Management
                  JOptionPane.showMessageDialog(null, "Selected Schedule is already booked please refresh the table and "
                          + "select different schedule");
              }else{
              dbo4.storeSystem(b);
              b = dbo4.retrieveSystem();
              int id = 1;
              int id1 = b.getAptHist().getAppointmentList().size();
              if(id1 > 0){
              Appointment tmp = b.getAptHist().getAppointmentList().get(id1-1);
              id = tmp.getId() + 1;}
              Appointment a = b.getAptHist().addAppointmentToAppointmentDb();
              a.setAppointmentDate((String)aptJTbl.getValueAt(selectedRow, 0));
              a.setPatientName(p.getName());
              a.setId(id);
              dbo4.storeSystem(b);
              populateTable();
              JOptionPane.showMessageDialog(null, "Appointment Created Successfully.\n" + 
              "Appointment Date and time : " +a.getAppointmentDate() + " Appointment Id : " + a.getId());
              }
          }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Schedule to Book appointment");
        }
        
    }//GEN-LAST:event_createAptJBtnActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void rfrshJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfrshJBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_rfrshJBtnActionPerformed

    private void patientNmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNmJTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aptJTbl;
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton createAptJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientNmJTxtField;
    private javax.swing.JButton rfrshJBtn;
    // End of variables declaration//GEN-END:variables
}
